# Cloudflare Worker API 서버
name = "overhaul-as-system-dev"
main = "src/worker/index.ts"
compatibility_date = "2025-07-26"
compatibility_flags = ["nodejs_compat"]

# 환경변수 (Development)
[vars]
JWT_SECRET = "overhaul-as-system-jwt-secret-key-2025"
ENVIRONMENT = "development"
API_VERSION = "v1"

# KV 바인딩 (Development)
[[kv_namespaces]]
binding = "USERS"
id = "f1124fd435d74ec8a11506c73d49c99c"

# D1 바인딩 (Development - 기존 DB 사용)
[[d1_databases]]
binding = "DB"
database_name = "overhaul-as-system"
database_id = "55cd5a26-5ad5-4e65-bfe4-f6e21e323667"

[env.production]
name = "overhaul-as-system-prod"
[env.production.vars]
JWT_SECRET = "overhaul-as-system-jwt-secret-key-2025"
ENVIRONMENT = "production"
API_VERSION = "v1"

[[env.production.kv_namespaces]]
binding = "USERS"
id = "18b6c08051ca4296994f5ee7629e1199"

[[env.production.d1_databases]]
binding = "DB"
database_name = "overhaul-as-system"
database_id = "55cd5a26-5ad5-4e65-bfe4-f6e21e323667"

# 모든 리소스가 dev/prod로 분리됨
