name = "overhaul-as-system"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-07-26"

# 환경변수
[vars]
JWT_SECRET = "overhaul-as-system-jwt-secret-key-2025"
ENVIRONMENT = "development"
API_VERSION = "v1"

[env.production]
name = "overhaul-as-system-prod"

[env.staging]
name = "overhaul-as-system-staging"

[env.development]
name = "overhaul-as-system-dev"
compatibility_date = "2025-07-26"
compatibility_flags = ["nodejs_compat"]

# CORS 설정 추가
[[env.development.cors]]
allowed_origins = ["http://localhost"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["*"]
max_age = 86400

[[kv_namespaces]]
binding = "USERS"
id = "432ab65981814ad8996c68476fe05e54"
preview_id = "5d8517f5435c4f18bd0359085f415ecb"

[[d1_databases]]
binding = "DB"
database_name = "overhaul-as-system"
database_id = "55cd5a26-5ad5-4e65-bfe4-f6e21e323667"

# Next.js assets are handled by the worker directly
