name: Deploy Development

on:
  push:
    branches:
      - dev

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    name: Deploy Worker API (Dev)
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy Worker (Development)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy

      - name: Run Database Migrations (Development)
        run: npm run db:migrate:dev:remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-pages:
    runs-on: ubuntu-latest
    name: Deploy Frontend (Dev)
    needs: deploy-worker
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Pages (Development)
        run: npm run build:pages
        env:
          API_BASE_URL: https://overhaul-as-system-dev.ravit-cloud.workers.dev
          ENVIRONMENT: development
          FRONTEND_URL: https://overhaul-frontend-dev.pages.dev

      - name: Deploy Pages (Development)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy out --project-name=overhaul-frontend-dev
