name: Deploy Overhaul System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    name: Deploy Worker API
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
        env:
          NODE_VERSION: 18

  deploy-pages:
    runs-on: ubuntu-latest
    name: Deploy Frontend
    needs: deploy-worker
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Pages
        run: npm run build:pages
        env:
          API_BASE_URL: https://overhaul-as-system.ravit-cloud.workers.dev

      - name: Deploy Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy out --project-name=overhaul-frontend
        env:
          NODE_VERSION: 18
